default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: christian_hacker_api_development

test:
  <<: *default
  database: christian_hacker_api_test  

production:
  <<: *default
  database: christian_hacker_api_production
  username: christian_hacker_api
  password: <%= ENV['CHRISTIAN_HACKER_API_DATABASE_PASSWORD'] %>